---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1643084/public_html/monitoring/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH